version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    working_dir: /srv/search
    volumes:
      - ..:/srv/search
    command: "flask run --host=0.0.0.0"
    ports:
      - "5000:5000"
    env_file:
      - dev.env